# serverless.yml
myNextApplication:
  component: "@sls-next/serverless-component@latest"
  inputs:
    name:
      defaultLambda: DefaultLambda #Default Lambda의 이름 설정
      imageLambda: ImageLambda # Image Lambda의 이름 설정
    bucketRegion: "ap-northeast-2" # S3 Bucket 지역 설정
    bucketName: "bq28ed-w5kkxnn"
    cloudfront:
      distributionId: "E36B8MVMNENKGO"
      comment: "next deploy" # CloudFront 설명 설정
